apiVersion: v1
kind: Service
metadata:
  name: jibri-pod-controller
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: jibri-pod-controller
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080